//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace app_login
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int ID_Admin { get; set; }
        public string Nume { get; set; }
        public string Prenume { get; set; }
        public int ID_User { get; set; }
    
        public virtual User User { get; set; }
    }
}
