//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace app_login
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taught_subjects
    {
        public int ID_Prof { get; set; }
        public int ID_Subj { get; set; }
        public Nullable<int> ceva { get; set; }
    
        public virtual Profesor Profesor { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
